package dev.natowb.natosatlas.core.utils;

import java.util.HashMap;
import java.util.Map;

public class ColorMapperUtil {

    public static final Map<Integer, Integer> COLORS = new HashMap<>();

    public static int BLOCK_AIR_ID = 0;

    public static int BLOCK_STONE_ID = 1;
    public static int BLOCK_GRASS_ID = 2;
    public static int BLOCK_DIRT_ID = 3;
    public static int BLOCK_COBBLESTONE_ID = 4;
    public static int BLOCK_PLANKS_ID = 5;
    public static int BLOCK_SAPLING_ID = 6;
    public static int BLOCK_BEDROCK_ID = 7;
    public static int BLOCK_WATER_MOVING_ID = 8;
    public static int BLOCK_WATER_STILL_ID = 9;
    public static int BLOCK_LAVA_MOVING_ID = 10;
    public static int BLOCK_LAVA_STILL_ID = 11;
    public static int BLOCK_SAND_ID = 12;
    public static int BLOCK_GRAVEL_ID = 13;
    public static int BLOCK_ORE_GOLD_ID = 14;
    public static int BLOCK_ORE_IRON_ID = 15;
    public static int BLOCK_ORE_COAL_ID = 16;
    public static int BLOCK_WOOD_ID = 17;
    public static int BLOCK_LEAVES_ID = 18;
    public static int BLOCK_SPONGE_ID = 19;
    public static int BLOCK_GLASS_ID = 20;
    public static int BLOCK_ORE_LAPIS_ID = 21;
    public static int BLOCK_BLOCK_LAPIS_ID = 22;
    public static int BLOCK_DISPENSER_ID = 23;
    public static int BLOCK_SANDSTONE_ID = 24;
    public static int BLOCK_MUSIC_BLOCK_ID = 25;
    public static int BLOCK_BED_ID = 26;
    public static int BLOCK_RAIL_POWERED_ID = 27;
    public static int BLOCK_RAIL_DETECTOR_ID = 28;
    public static int BLOCK_PISTON_STICKY_BASE_ID = 29;
    public static int BLOCK_WEB_ID = 30;
    public static int BLOCK_TALL_GRASS_ID = 31;
    public static int BLOCK_DEAD_BUSH_ID = 32;
    public static int BLOCK_PISTON_BASE_ID = 33;
    public static int BLOCK_PISTON_EXTENSION_ID = 34;
    public static int BLOCK_PISTON_MOVING_ID = 36;
    public static int BLOCK_FLOWER_YELLOW_ID = 37;
    public static int BLOCK_FLOWER_RED_ID = 38;
    public static int BLOCK_MUSHROOM_BROWN_ID = 39;
    public static int BLOCK_MUSHROOM_RED_ID = 40;
    public static int BLOCK_BLOCK_GOLD_ID = 41;
    public static int BLOCK_BLOCK_IRON_ID = 42;
    public static int BLOCK_STONE_SLAB_DOUBLE_ID = 43;
    public static int BLOCK_STONE_SLAB_SINGLE_ID = 44;
    public static int BLOCK_BRICK_ID = 45;
    public static int BLOCK_TNT_ID = 46;
    public static int BLOCK_BOOKSHELF_ID = 47;
    public static int BLOCK_COBBLESTONE_MOSSY_ID = 48;
    public static int BLOCK_OBSIDIAN_ID = 49;
    public static int BLOCK_TORCH_ID = 50;
    public static int BLOCK_FIRE_ID = 51;
    public static int BLOCK_MOB_SPAWNER_ID = 52;
    public static int BLOCK_STAIRS_WOOD_ID = 53;
    public static int BLOCK_CHEST_ID = 54;
    public static int BLOCK_REDSTONE_WIRE_ID = 55;
    public static int BLOCK_ORE_DIAMOND_ID = 56;
    public static int BLOCK_BLOCK_DIAMOND_ID = 57;
    public static int BLOCK_WORKBENCH_ID = 58;
    public static int BLOCK_CROPS_ID = 59;
    public static int BLOCK_FARMLAND_ID = 60;
    public static int BLOCK_FURNACE_IDLE_ID = 61;
    public static int BLOCK_FURNACE_ACTIVE_ID = 62;
    public static int BLOCK_SIGN_POST_ID = 63;
    public static int BLOCK_DOOR_WOOD_ID = 64;
    public static int BLOCK_LADDER_ID = 65;
    public static int BLOCK_RAIL_ID = 66;
    public static int BLOCK_STAIRS_STONE_ID = 67;
    public static int BLOCK_SIGN_WALL_ID = 68;
    public static int BLOCK_LEVER_ID = 69;
    public static int BLOCK_PRESSURE_PLATE_STONE_ID = 70;
    public static int BLOCK_DOOR_IRON_ID = 71;
    public static int BLOCK_PRESSURE_PLATE_WOOD_ID = 72;
    public static int BLOCK_ORE_REDSTONE_ID = 73;
    public static int BLOCK_ORE_REDSTONE_GLOWING_ID = 74;
    public static int BLOCK_REDSTONE_TORCH_IDLE_ID = 75;
    public static int BLOCK_REDSTONE_TORCH_ACTIVE_ID = 76;
    public static int BLOCK_BUTTON_ID = 77;
    public static int BLOCK_SNOW_ID = 78;
    public static int BLOCK_ICE_ID = 79;
    public static int BLOCK_SNOW_BLOCK_ID = 80;
    public static int BLOCK_CACTUS_ID = 81;
    public static int BLOCK_CLAY_ID = 82;
    public static int BLOCK_REED_ID = 83;
    public static int BLOCK_JUKEBOX_ID = 84;
    public static int BLOCK_FENCE_ID = 85;
    public static int BLOCK_PUMPKIN_ID = 86;
    public static int BLOCK_NETHERRACK_ID = 87;
    public static int BLOCK_SOUL_SAND_ID = 88;
    public static int BLOCK_GLOWSTONE_ID = 89;
    public static int BLOCK_PORTAL_ID = 90;
    public static int BLOCK_PUMPKIN_LANTERN_ID = 91;
    public static int BLOCK_CAKE_ID = 92;
    public static int BLOCK_REDSTONE_REPEATER_IDLE_ID = 93;
    public static int BLOCK_REDSTONE_REPEATER_ACTIVE_ID = 94;
    public static int BLOCK_LOCKED_CHEST_ID = 95;
    public static int BLOCK_TRAPDOOR_ID = 96;

    static {
        COLORS.put(BLOCK_AIR_ID, 0x000000);
        COLORS.put(BLOCK_STONE_ID, 0x707070);
        COLORS.put(BLOCK_GRASS_ID, 0x7FB238);
        COLORS.put(BLOCK_DIRT_ID, 0xB76A2F);
        COLORS.put(BLOCK_COBBLESTONE_ID, 0x707070);
        COLORS.put(BLOCK_PLANKS_ID, 0x685332);
        COLORS.put(BLOCK_SAPLING_ID, 0x007C00);
        COLORS.put(BLOCK_BEDROCK_ID, 0x707070);
        COLORS.put(BLOCK_WATER_MOVING_ID, 0x4040FF);
        COLORS.put(BLOCK_WATER_STILL_ID, 0x4040FF);
        COLORS.put(BLOCK_LAVA_MOVING_ID, 0xFF0000);
        COLORS.put(BLOCK_LAVA_STILL_ID, 0xFF0000);
        COLORS.put(BLOCK_SAND_ID, 0xF7E9A3);
        COLORS.put(BLOCK_GRAVEL_ID, 0xF7E9A3);
        COLORS.put(BLOCK_ORE_GOLD_ID, 0x707070);
        COLORS.put(BLOCK_ORE_IRON_ID, 0x707070);
        COLORS.put(BLOCK_ORE_COAL_ID, 0x707070);
        COLORS.put(BLOCK_WOOD_ID, 0x685332);
        COLORS.put(BLOCK_LEAVES_ID, 0x007C00);
        COLORS.put(BLOCK_SPONGE_ID, 0xA7A7A7);
        COLORS.put(BLOCK_GLASS_ID, 0x000000);
        COLORS.put(BLOCK_ORE_LAPIS_ID, 0x707070);
        COLORS.put(BLOCK_BLOCK_LAPIS_ID, 0x707070);
        COLORS.put(BLOCK_DISPENSER_ID, 0x707070);
        COLORS.put(BLOCK_SANDSTONE_ID, 0x707070);
        COLORS.put(BLOCK_MUSIC_BLOCK_ID, 0x685332);
        COLORS.put(BLOCK_BED_ID, 0xA7A7A7);
        COLORS.put(BLOCK_RAIL_POWERED_ID, 0x000000);
        COLORS.put(BLOCK_RAIL_DETECTOR_ID, 0x000000);
        COLORS.put(BLOCK_PISTON_STICKY_BASE_ID, 0x707070);
        COLORS.put(BLOCK_WEB_ID, 0xA7A7A7);
        COLORS.put(BLOCK_TALL_GRASS_ID, 0x007C00);
        COLORS.put(BLOCK_DEAD_BUSH_ID, 0x007C00);
        COLORS.put(BLOCK_PISTON_BASE_ID, 0x707070);
        COLORS.put(BLOCK_PISTON_EXTENSION_ID, 0x707070);
        COLORS.put(BLOCK_PISTON_MOVING_ID, 0x707070);
        COLORS.put(BLOCK_FLOWER_YELLOW_ID, 0x007C00);
        COLORS.put(BLOCK_FLOWER_RED_ID, 0x007C00);
        COLORS.put(BLOCK_MUSHROOM_BROWN_ID, 0x007C00);
        COLORS.put(BLOCK_MUSHROOM_RED_ID, 0x007C00);
        COLORS.put(BLOCK_BLOCK_GOLD_ID, 0xA7A7A7);
        COLORS.put(BLOCK_BLOCK_IRON_ID, 0xA7A7A7);
        COLORS.put(BLOCK_STONE_SLAB_DOUBLE_ID, 0x707070);
        COLORS.put(BLOCK_STONE_SLAB_SINGLE_ID, 0x707070);
        COLORS.put(BLOCK_BRICK_ID, 0x707070);
        COLORS.put(BLOCK_TNT_ID, 0xFF0000);
        COLORS.put(BLOCK_BOOKSHELF_ID, 0x685332);
        COLORS.put(BLOCK_COBBLESTONE_MOSSY_ID, 0x707070);
        COLORS.put(BLOCK_OBSIDIAN_ID, 0x707070);
        COLORS.put(BLOCK_TORCH_ID, 0x000000);
        COLORS.put(BLOCK_FIRE_ID, 0x000000);
        COLORS.put(BLOCK_MOB_SPAWNER_ID, 0x707070);
        COLORS.put(BLOCK_STAIRS_WOOD_ID, 0x685332);
        COLORS.put(BLOCK_CHEST_ID, 0x685332);
        COLORS.put(BLOCK_REDSTONE_WIRE_ID, 0x000000);
        COLORS.put(BLOCK_ORE_DIAMOND_ID, 0x707070);
        COLORS.put(BLOCK_BLOCK_DIAMOND_ID, 0xA7A7A7);
        COLORS.put(BLOCK_WORKBENCH_ID, 0x685332);
        COLORS.put(BLOCK_CROPS_ID, 0x007C00);
        COLORS.put(BLOCK_FARMLAND_ID, 0xB76A2F);
        COLORS.put(BLOCK_FURNACE_IDLE_ID, 0x707070);
        COLORS.put(BLOCK_FURNACE_ACTIVE_ID, 0x707070);
        COLORS.put(BLOCK_SIGN_POST_ID, 0x685332);
        COLORS.put(BLOCK_DOOR_WOOD_ID, 0x685332);
        COLORS.put(BLOCK_LADDER_ID, 0x000000);
        COLORS.put(BLOCK_RAIL_ID, 0x000000);
        COLORS.put(BLOCK_STAIRS_STONE_ID, 0x707070);
        COLORS.put(BLOCK_SIGN_WALL_ID, 0x685332);
        COLORS.put(BLOCK_LEVER_ID, 0x000000);
        COLORS.put(BLOCK_PRESSURE_PLATE_STONE_ID, 0x707070);
        COLORS.put(BLOCK_DOOR_IRON_ID, 0xA7A7A7);
        COLORS.put(BLOCK_PRESSURE_PLATE_WOOD_ID, 0x685332);
        COLORS.put(BLOCK_ORE_REDSTONE_ID, 0x707070);
        COLORS.put(BLOCK_ORE_REDSTONE_GLOWING_ID, 0x707070);
        COLORS.put(BLOCK_REDSTONE_TORCH_IDLE_ID, 0x000000);
        COLORS.put(BLOCK_REDSTONE_TORCH_ACTIVE_ID, 0x000000);
        COLORS.put(BLOCK_BUTTON_ID, 0x000000);
        COLORS.put(BLOCK_SNOW_ID, 0xFFFFFF);
        COLORS.put(BLOCK_ICE_ID, 0xA0A0FF);
        COLORS.put(BLOCK_SNOW_BLOCK_ID, 0xFFFFFF);
        COLORS.put(BLOCK_CACTUS_ID, 0x007C00);
        COLORS.put(BLOCK_CLAY_ID, 0xA4A8B8);
        COLORS.put(BLOCK_REED_ID, 0x007C00);
        COLORS.put(BLOCK_JUKEBOX_ID, 0x685332);
        COLORS.put(BLOCK_FENCE_ID, 0x685332);
        COLORS.put(BLOCK_PUMPKIN_ID, 0x007C00);
        COLORS.put(BLOCK_NETHERRACK_ID, 0x707070);
        COLORS.put(BLOCK_SOUL_SAND_ID, 0xF7E9A3);
        COLORS.put(BLOCK_GLOWSTONE_ID, 0x707070);
        COLORS.put(BLOCK_PORTAL_ID, 0x000000);
        COLORS.put(BLOCK_PUMPKIN_LANTERN_ID, 0x007C00);
        COLORS.put(BLOCK_CAKE_ID, 0x000000);
        COLORS.put(BLOCK_REDSTONE_REPEATER_IDLE_ID, 0x000000);
        COLORS.put(BLOCK_REDSTONE_REPEATER_ACTIVE_ID, 0x000000);
        COLORS.put(BLOCK_LOCKED_CHEST_ID, 0x685332);
        COLORS.put(BLOCK_TRAPDOOR_ID, 0x685332);
    }

    public static int get(int blockId) {
        return COLORS.getOrDefault(blockId, 0xFFFF0000);
    }
}
